version: '3.7'

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=DontHackMePlease
      - POSTGRES_USER=bobsty
      - POSTGRES_DB=bobii
    volumes:
      - ./data/postgres:/var/lib/postgresql/data"

  bobii:
    image: ghcr.io/bobsty-0/bobii:bobiiupdates
    volumes:
      - ./config.json:/app/Config.json:ro
