// <auto-generated />
using System;
using Bobii.src.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bobii.Migrations
{
    [DbContext(typeof(BobiiEntities))]
    [Migration("20220222073839_Added_deletedate_to_TempChannel_Table")]
    partial class Added_deletedate_to_TempChannel_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.caption", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("de")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("en")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("msgid")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("id");

                    b.ToTable("Captions");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.commands", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("command")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("de")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("en")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.content", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("de")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("en")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("msgid")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("id");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.createtempchannels", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("channelsize")
                        .HasColumnType("integer");

                    b.Property<decimal>("createchannelid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("tempchannelname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("textchannel")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("CreateTempChannels");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.filterlink", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("filterlinkactive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("FilterLink");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.filterlinklogs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("channelid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("FilterLinkLogs");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.filterlinkoptions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("bezeichnung")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("linkbody")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.ToTable("FilterLinkOptions");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.filterlinksguild", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("bezeichnung")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("FilterLinksGuild");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.filterlinkuserguild", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("userid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("FilterLinkUserGuild");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.filterwords", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("filterword")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("replaceword")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("id");

                    b.ToTable("FilterWords");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.language", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("langugeshort")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.tempchannels", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("channelid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("channelownerid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("count")
                        .HasColumnType("integer");

                    b.Property<decimal?>("createchannelid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("deletedate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("textchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("TempChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
