// <auto-generated />
using System;
using Bobii.src.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bobii.Migrations
{
    [DbContext(typeof(BobiiEntities))]
    [Migration("20220917074833_added_tempchanneluserconfigs_table")]
    partial class added_tempchanneluserconfigs_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.createtempchannels", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("channelsize")
                        .HasColumnType("integer");

                    b.Property<decimal>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("delay")
                        .HasColumnType("integer");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("tempchannelname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("CreateTempChannels");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.language", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("guildid")
                        .HasMaxLength(18)
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("langugeshort")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.tempchannels", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("channelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("channelownerid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("count")
                        .HasColumnType("integer");

                    b.Property<decimal?>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("deletedate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("TempChannels");
                });

            modelBuilder.Entity("Bobii.src.EntityFramework.Entities.tempchanneluserconfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("channelsize")
                        .HasColumnType("integer");

                    b.Property<decimal>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("tempchannelname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("userid")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("TempChannelUserConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
