// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bobii_rework.EntityFramework;

#nullable disable

namespace bobii_rework.Migrations
{
    [DbContext(typeof(BobiiContext))]
    [Migration("20240610185232_AddCommandColorRGBColumn")]
    partial class AddCommandColorRGBColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.InterfaceInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomCommandColorRGBA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomCommandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EmoteId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("InterfaceInformations");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.autoscalecategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("autodelete")
                        .HasColumnType("integer");

                    b.Property<decimal>("categoryid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("channelname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("channelsize")
                        .HasColumnType("integer");

                    b.Property<int>("emptychannelnumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("AutoScaleCategories");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.createtempchannels", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("autodelete")
                        .HasColumnType("integer");

                    b.Property<int?>("channelsize")
                        .HasColumnType("integer");

                    b.Property<decimal>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("delay")
                        .HasColumnType("integer");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("tempchannelname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("CreateTempChannels");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.tempchannels", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("autoscale")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("autoscalercategoryid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("channelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("channelownerid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("count")
                        .HasColumnType("integer");

                    b.Property<decimal?>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("deletedate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("unixtimestamp")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("TempChannels");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.tempchanneluserconfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("autodelete")
                        .HasColumnType("integer");

                    b.Property<int?>("channelsize")
                        .HasColumnType("integer");

                    b.Property<decimal>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("tempchannelname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("userid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("usernamemode")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("TempChannelUserConfigs");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.tempcommands", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("commandname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("enabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("guildguid")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.usedfunctions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("affecteduserid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("channelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("doneat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("function")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("isuser")
                        .HasColumnType("boolean");

                    b.Property<decimal>("userid")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("UsedFunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
