// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bobii_rework.EntityFramework;

#nullable disable

namespace bobii_rework.Migrations
{
    [DbContext(typeof(BobiiContext))]
    [Migration("20260303181323_AddedIsCommandColumnToInterfaceInformation")]
    partial class AddedIsCommandColumnToInterfaceInformation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.CreateTempChannel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("autodelete")
                        .HasColumnType("integer");

                    b.Property<int?>("channelsize")
                        .HasColumnType("integer");

                    b.Property<decimal>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("delay")
                        .HasColumnType("integer");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("tempchannelname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("CreateTempChannels");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.Emote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Animated")
                        .HasColumnType("boolean");

                    b.Property<decimal>("EmoteId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("GuidId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Emotes");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.InterfaceInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomCommandBackgroundColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomCommandForeColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomCommandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmoteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsCommand")
                        .HasColumnType("boolean");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InterfaceInformations");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.TempChannel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<bool>("autoscale")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("autoscalercategoryid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("channelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("channelownerid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("count")
                        .HasColumnType("integer");

                    b.Property<decimal?>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("deletedate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("unixtimestamp")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("TempChannels");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.TempChannelUserConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("autodelete")
                        .HasColumnType("integer");

                    b.Property<int?>("channelsize")
                        .HasColumnType("integer");

                    b.Property<decimal>("createchannelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("tempchannelname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("userid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("usernamemode")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("TempChannelUserConfigs");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.TempCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CreateChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("bobii_rework.Entities.EntityFramework.UsedFunction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("affecteduserid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("channelid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("doneat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("function")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("guildid")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("isuser")
                        .HasColumnType("boolean");

                    b.Property<decimal>("userid")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("id");

                    b.ToTable("UsedFunctions");
                });
#pragma warning restore 612, 618
        }
    }
}
